name: Publish docs for released version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of this doc
        required: true
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name ${{ secrets.GIT_NAME }}
      - run: git config user.email ${{ secrets.GIT_EMAIL }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material mike

      - run: mike deploy --push --force --update-alias ${GITHUB_REF#refs/tags/v} latest
        if: ${{ github.event_name == 'release' }}

      - run: mike deploy --push --force --update-alias ${{ github.event.inputs.version }} latest
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - run: mike set-default latest

      - run: mkdocs gh-deploy --force
